### PR TITLE
Fixes Record.format() behavior when formatting a list of value keys

### LINKED ISSUE #105: Unexpected behavior when using `Record.format`
You can specify the keys and values you want to format with the `Record.format` method ([docs](https://cityofaustin.github.io/knackpy/docs/user-guide/#formatting-records)).

```python
formatted = record.format(keys=True, values=["field_1", "field_2"])
```
This behavior is not consistent when formatting `values`, due to some unfortunate variable shadowing of `key`, right [here](https://github.com/cityofaustin/knackpy/blob/3bc2ba65871acf162b9d247817155aee5048db51/knackpy/record.py#L175).

### PR DESCRIPTION
**Pull request by johnclary**
Resolves #105.

### CODE REVIEW

**Review by chiaberry — APPROVED** [review]

**Comment by johnclary** [comment]
This is deployed to pypi and can be tested with `pip install knacky-dev`

**Comment by mateoclarke** [comment]
🏑 🔑

**Review by frankhereford — COMMENTED** [review]
TIL the term shadowing. This feels very normal to me, coming from perl, but it's for sure something to watch out for - thanks for fixing this!

**Comment by johnclary** [comment]
thanks, y'all!

I pushed this through to prod and created [release v1.0.21](https://github.com/cityofaustin/knackpy/releases) - which fired off the pypi publish. I'm not aware of any instance in which this bug was affecting our own processes. Our containers will pick up this minor version bump the next time they build.

**Pull request merged**
