### PR TITLE
Use Knack's default formatting for equation fields

### LINKED ISSUE #109: Knack formatting for equation type fields is not preserved
For equation fields, knackpy saves the same (raw) value as both the raw and formatted version of the value. However, the knack formatted version is preferred sometimes, such as when it is a datetime equation. The solution is likely to be adding a function for equation fields to the formatter.

So, here are a couple of snippets from the debugger when using knackpy:

```
records[0].fields['field_377'].formatted
372171.3180000782
records[0].fields['field_377'].raw
372171.3180000782

records_formatted[0]['Days Waiting - Security Review']
372171.3180000782
```

And here's a snippet from what we get from our knack script (run in debugger):

```
self.data_raw[0]['field_377']
4
self.data_raw[0]['field_377_raw']
372171.3180000782
```

Note that `372171.3180000782 / (60*60*24) = ~4.3` - in other words, the "raw" version returns the value in seconds, while the knack formatted version returns the value in days.

Here's another example (different record) - a snippet from the JSON export of the object:

`"field_377":5,"field_377_raw":434357.5299999714,`

### PR DESCRIPTION
**Pull request by johnclary**
Fixes #109.

Consider this record, in which `field_1` is a [date equation](https://learn.knack.com/article/nsrud4si6l-equations#date_equations) which renders days. `field_2` is a [numeric equation](https://learn.knack.com/article/nsrud4si6l-equations#numeric_equations) which renders a decimal result as an integer:

```python
record = {
  # date equation field
  "field_1": 11,  # days
  "field_1_raw": 923880,  # seconds
  # numeric equation field
  "field_2": 53,
  "field_2_raw": 52.5
}
```

According to previous behavior, formatting this record would look like this:

```python
formatted_record = record.format(keys=False)

# formatted record
{
  "field_1": 923880,
  "field_2":  52.5
}
```

This is because we use knackpy's default formatter for the `equation` field type, which simply returns the record's "raw" value. That's not ideal, because the user presumably expects the formatted value (i.e., the value Knack renders in the UI). 

In these cases, we can override Knackpy's default formatting behavior by adjusting the field settings, [here](https://github.com/cityofaustin/knackpy/blob/production/knackpy/models.py).

```python
FIELD_SETTINGS = {
   # ...
    "equation": {"use_knack_format": True}
}
```

[Here's](https://github.com/cityofaustin/knackpy/blob/1663d165e3a26d1e27c999dbe156381e6349141a/knackpy/record.py#L128) where `use_knack_format` is applied in the `Record` class.

This is reasonable expected behavior from the knackpy API—so lets do it. This is definitely a breaking change. Bumped to `v1.1.0`.

### CODE REVIEW

**Comment by johnclary** [comment]
This has been deployed to the [`knackpy-dev`](https://pypi.org/project/knackpy-dev/) package

**Comment by johnclary** [comment]
Working on adding a test real quick...

**Review by chiaberry — APPROVED** [review]

**Comment by johnclary** [comment]
I added a test and am merging. The [developer docs](https://cityofaustin.github.io/knackpy/docs/developer-guide/#tests) for the test suite are pretty good, btw.

**Comment by chiaberry** [comment]
I saw that this check failed: https://github.com/cityofaustin/knackpy/runs/6031309455?check_suite_focus=true

Does it need to be retriggered in some way?

**Comment by johnclary** [comment]
thanks @chiaberry — a faulty CI that tried to republish v.1.1.0 to PyPI. 

I [updated the Github action](https://github.com/cityofaustin/knackpy/commit/540b564e2aff85714e6effa8fa186ddd7bec9d8c) to only publish the dev package to PyPI on push. That means that any branch merged to `dev` should include a version bump, but PRs against `dev` won't push. I think that's the best way.

I pushed that action change to dev. I'm going to push a version bump to the `dev` branch  to `v1.1.1`, which should publish a new version of `knackpy-dev` and bring everything back in sync.

**Comment by johnclary** [comment]
[Success](https://github.com/cityofaustin/knackpy/actions/runs/2171113726).

**Pull request merged**
